[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[deploy.environmentVariables]]
name = "PORT"
value = "8000"

[[deploy.environmentVariables]]
name = "PYTHONPATH"
value = "/app"

[environments.production]
variables = { }
